<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <UniversalDevKitArtifactsRoot>$(MSBuildThisFileDirectory)..\..\!artifacts\</UniversalDevKitArtifactsRoot>
    <UniversalDevKitTargetPlatform Condition="'$(UniversalDevKitTargetPlatform)' == ''">Windows-$(Platform)</UniversalDevKitTargetPlatform>
    <OutDir>$(UniversalDevKitArtifactsRoot)$(UniversalDevKitTargetPlatform)\msbuild\$(MSBuildProjectName)\$(Configuration)\bin\</OutDir>
    <IntDir>$(UniversalDevKitArtifactsRoot)$(UniversalDevKitTargetPlatform)\msbuild\$(MSBuildProjectName)\$(Configuration)\obj\</IntDir>
  </PropertyGroup>
</Project>